Repository OpenPerpetuum/OPDB, pull requests merged in 2019-06, with the labels that each got.

#152 Fix the boost procedure datetime
  Staging_Dev/Proc_getExtensionSub_datetime_fix__2019_05_19.sql
Labels: Patch 11, bug

#153 Pit-Boss + new EP-boost item for loot
  Staging_Dev/PitBoss_and_EPboostitem_t0loot__2019_05_23.sql
Labels: Patch 11

#150 Welcome chat message
  Staging_Dev/20190508T014400Z_welcome_chat_message.sql
  apply_all.bat
Labels: Patch 11

#148 Itemshop: add pvp faction ammo to hersh
  Staging_Dev/Itemshop_pvpammo_hersh__2019_05_05.sql
Labels: Patch 11

#138 Blinder module + Blinder NPC changes to Hersh
  Staging_Dev/Blinder_moduleAndNPCs__2019_05_22.sql
Labels: Patch 11

#145 Welcome char bug fix + some extra
  Staging_Dev/Characters_welcomechar-bugfix__2019_04_25.sql
Labels: Patch 11, bug

#146 npcloots: Common kernel add to bosses, alpha 1, omega
  Staging_Dev/NpcLoots_alpha1_omega_bosses__2019_05_02.sql
Labels: Patch 11

#151 Localization init
  Staging_Dev/Server/data/customDictionary/0.json
  Staging_Dev/Server/data/customDictionary/2.json
Labels: Patch 11

#156 README clean up and updates
  CONTRIBUTING.md
  README.md
Labels: enhancement, help wanted

#147 Beta npc overhaul
  Staging_Dev/NPCs_Beta1__2019_05_02.sql
  Staging_Dev/NPCs_Beta2__2019_05_02.sql
Labels: Patch 11

#157 Missing silgium orders fixed
  Staging_Dev/Itemshop_Inserts_missing-silgium__2019_06_07.sql
Labels: Patch 11, bug

#159 Localization tweaks and fixes (6/10/2019)
  Staging_Dev/Server/data/customDictionary/0.json
  Staging_Dev/Server/data/customDictionary/2.json
Labels: Patch 11, bug

#161 EP bonus item price x0.25, duration 2x
  Staging_Dev/Itemshop_EntityDefaults_updates_epbonusitem__2019_06_12.sql
  Staging_Dev/Server/data/customDictionary/0.json
Labels: Patch 11, enhancement
