Repository OpenPerpetuum/OPDB, pull requests merged in 2019-07, with the labels that each got.

#149 Make the apply_all script to be more easily scriptable
  apply_all.bat
Labels: enhancement

#163 Patch 11 cleanup
  Patches/Live_11/Raw_SQL/20190508T014400Z_welcome_chat_message.sql
  Patches/Live_11/Raw_SQL/Blinder_moduleAndNPCs__2019_05_22.sql
  Patches/Live_11/Raw_SQL/Characters_welcomechar-bugfix__2019_04_25.sql
  Patches/Live_11/Raw_SQL/Itemshop_EntityDefaults_updates_epbonusitem__2019_06_12.sql
  Patches/Live_11/Raw_SQL/Itemshop_Inserts_missing-silgium__2019_06_07.sql
  Patches/Live_11/Raw_SQL/Itemshop_pvpammo_hersh__2019_05_05.sql
  Patches/Live_11/Raw_SQL/NPCs_Beta1__2019_05_02.sql
  Patches/Live_11/Raw_SQL/NPCs_Beta2__2019_05_02.sql
  Patches/Live_11/Raw_SQL/NpcLoots_alpha1_omega_bosses__2019_05_02.sql
  Patches/Live_11/Raw_SQL/PitBoss_and_EPboostitem_t0loot__2019_05_23.sql
  Patches/Live_11/Raw_SQL/Proc_getExtensionSub_datetime_fix__2019_06_30.sql
  Patches/Live_11/Server/data/customDictionary/0.json
  Patches/Live_11/Server/data/customDictionary/2.json
  Patches/Live_11/live_patch_11.sql
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_0__init__2018_10_15.sql
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_1__npctweak__2018_10_27.sql
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_2__loot_killep_npcmods_respawnrate__2019_01_13.sql
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_3__loot_npc_fields__2019_01_27.sql
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_4__fitting_modifiers_loot_updates__2019_03_30.sql
  Tools/DEV_ONLY_reputation_set.sql
  apply_all.bat
Labels: Patch 11

#158 SAPs: masking decrease
  Staging_Dev/SAPs_masking_decr__2019_06_10.sql
Labels: Patch 12

#160 World layout redesign for gamma prep
  Staging_Dev/Zones_updates__2019_06_10.sql
Labels: Patch 12

#164 Market: Intrusion scanner charge price reduce
  Staging_Dev/Market_intrusion_charge__2019 _07_06.sql
Labels: Patch 12

#166 Pitboss difficulty tweaks
  Staging_Dev/Pitboss_live_tweak01__2019_07_13.sql
Labels: Patch 12

#165 Syndicate combat chassis bonus fix for falloff
  Staging_Dev/ChassisBonus_synd_falloff_fix__2019_07_13.sql
Labels: Patch 12, bug

#167 Balance: missing armor plate tweaks
  Staging_Dev/Balance_armorplates_missedartifacttype__2019_07_13.sql
Labels: Patch 12
