Repository OpenPerpetuum/OPDB, pull requests merged in 2019-02, with the labels that each got.

#119 Balance: Cronus gets a gun
  Staging_Dev/def_cronus_chassis__2019_01_27_00_45_20.sql
Labels: Patch 9, enhancement

#118 Pitboss v4
  Staging_Dev/DEV_Testing_Only/NPC_Pitboss_0_3__loot_npc_fields__2019_01_27.sql
Labels: Internal testing only

#121 Keep the change you filthy animal
  Staging_Dev/Itemshop_paintprice__2019_02_03.sql
Labels: Patch 9

#120 Artifactloot: CT flat droprate increase
  Staging_Dev/Artifactloot_CTdroprate_flatfix__2019_02_02.sql
Labels: Patch 9

#123 Batch script to apply all the patches
  apply_all.bat
Labels: good first issue

#122 Artifact Fixes - consolidate and order
  Staging_Dev/ArtifactLoot_artifactSpawn_conslidated-fixes__2019_02_06.sql
  Staging_Dev/Artifactloot_CTdroprate_flatfix__2019_02_02.sql
  Staging_Dev/Artifactspawninfo_alpha_balance_rates_generated.sql
Labels: Patch 9

#117 Bug fix on EP bonus item
  Staging_Dev/01_EPItemPatch.sql
Labels: Patch 9, bug
